[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://loregg.netlify.app/join"
  to = "https://discord.gg/FJGNFZpMmt"
  status = 301
  force = true
